services:
  db:
    image: neo4j:latest
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/pass
      NEO4J_dbms_logs_debug_level: DEBUG
      neo4j:server:uri: bolt://localhost:7687
    networks:
      - yandex-disk

  app:
    container_name: app
    image: 'yandex-disk:latest'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - "db:database"
    ports:
      - "8080:8080"
    networks:
      - yandex-disk


networks:
  yandex-disk:
    name: yandex-disk-net
    driver: bridge
    ipam:
      driver: default

